CREATE DATABASE point_of_sale_db;

USE point_of_sale_db;

CREATE TABLE product (
	id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(100) NOT NULL,
    quantity DECIMAL(10,2) UNSIGNED NOT NULL,
    unit VARCHAR(50) NOT NULL,
    unit_price DECIMAL(10,2) UNSIGNED NOT NULL
);

CREATE TABLE sale (
	id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    date_of_purchase DATETIME NOT NULL,
    total_price DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0,
    cash_received DECIMAL(10,2) UNSIGNED NOT NULL,
    `change` DECIMAL(10,2) UNSIGNED NOT NULL
);

CREATE TABLE sale_detail (
	id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    quantity DECIMAL(10,2) UNSIGNED NOT NULL,
    price DECIMAL(10,2) UNSIGNED NOT NULL,
    product_id BIGINT UNSIGNED NOT NULL,
    sale_id BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY(product_id) REFERENCES product(id),
    FOREIGN KEY(sale_id) REFERENCES sale(id)
);